POST http://localhost:10000/api/v1/auth/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "password123"
}

###

GET http://localhost:10000/api/v1/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyIiwiaWF0IjoxNzYxMjE3MjIzLCJleHAiOjE3NjEyMjA4MjN9.LpxXzCTTscjJI0bO8gLu7kqzyJymx-thQyB68A3SpGU

###

POST http://localhost:10000/api/v1/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyIiwiaWF0IjoxNzYxMjE3MjIzLCJleHAiOjE3NjEyMjA4MjN9.LpxXzCTTscjJI0bO8gLu7kqzyJymx-thQyB68A3SpGU
Content-Type: application/json

{
  "title": "New Task",
  "description": "Task created via HTTP test",
  "status": "pending"
}

###
GET http://localhost:10000/api/v1/tasks/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyIiwiaWF0IjoxNzYxMjE3MjIzLCJleHAiOjE3NjEyMjA4MjN9.LpxXzCTTscjJI0bO8gLu7kqzyJymx-thQyB68A3SpGU